---
providers:
  # See the basic example for descriptions of the bulk of this config file, here
  # we'll focus on things related to octodns-dump
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config

  # In a real setup this would be your existing DNS provider where all of your
  # zones are configured. E.g. Route53, Azure, Cloudflare, NS1, ... Here it's
  # using a second YamlProvider so that the example can be self contained and
  # will work for anyone. For information on how to configure your provider see
  # its README.md
  some-provider:
    class: octodns.provider.yaml.YamlProvider
    directory: ./target
    # This is a rarely used option that tells the YamlProvider that it should
    # load existing records from disk rather than assume nothing exists
    # created every a plan is made.
    # TODO:
    #populate_existing: true

zones:

  # We're using dynamic zone config to dynamically build the list of configured
  # zones using the sources & targets below for each.
  '*':
    sources:
      - config
    targets:
      - some-provider
