name: OctoDNS
on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Tested versions based on dates in https://devguide.python.org/versions/#versions
        python-version: [${{fromJson(secrets.PYTHON_VERSIONS_ACTIVE)}}]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install virtualenv
      - name: CI Build
        run: |
          ./script/cibuild
      - name: Store Code Coverage Data
        # if the previous step(s) failed try anyways
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-${{ matrix.python-version }}
          path: |
            .coverage
            coverage.xml
            htmlcov
  setup-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: x64
      - name: CI setup.py
        run: |
          ./script/cibuild-setup-py
