name: OctoDNS Modules
on:
  workflow_dispatch: # option to run manually if/when needed
  pull_request_review:
    types: [submitted]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - asyncon/octoblox
          - octodns/octodns-azure
          - octodns/octodns-bind
          - octodns/octodns-cloudflare
          - octodns/octodns-constellix
          - octodns/octodns-ddns
          - octodns/octodns-digitalocean
          - octodns/octodns-dnsimple
          - octodns/octodns-dnsmadeeasy
          - octodns/octodns-dyn
          - octodns/octodns-easydns
          - octodns/octodns-edgedns
          - octodns/octodns-etchosts
          - octodns/octodns-gandi
          - octodns/octodns-gcore
          - octodns/octodns-googlecloud
          - octodns/octodns-hetzner
          - octodns/octodns-mythicbeasts
          - octodns/octodns-ns1
          - octodns/octodns-ovh
          - octodns/octodns-powerdns
          - octodns/octodns-rackspace
          - octodns/octodns-route53
          - octodns/octodns-selectel
          - octodns/octodns-transip
          - octodns/octodns-ultra
          # has been failing for a while now and afaict not related to octoDNS
          # changes commenting out on 2023-07-30, will check on it again in at
          # some point in the future and either re-enable or delete it.
          #- sukiyaki/octodns-netbox
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.PYTHON_VERSION_CURRENT }}
          architecture: x64
      - name: Test Module
        run: |
          ./script/test-module ${{ matrix.module }}
